version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=sqlite:///./diplocyber.db
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
    volumes:
      - .:/app
    restart: always
    networks:
      - diplocyber-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - diplocyber-network

networks:
  diplocyber-network:
    driver: bridge
